spring:
  profiles:
    active:
      - inMemoryDB
      - development
---
spring:
  profiles: inMemoryDB
  datasource:
    url: jdbc:h2:mem:assignment3db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
---
spring:
  # local
  profiles: development
image:
    # path to get the image
    imageServerDirectory: /Users/iammiind/Desktop/assignment3/images/
---
spring:
  # deploy into the server
  profiles: deploy
image:
    # path to get the image
    imageServerDirectory: -------